<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard_model extends CI_Model
{

    public $table = 'data_tes';
    public $id = 'id_data_tes';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_data_tes', $q);
	$this->db->or_like('id_santri', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jenis_izin', $q);
    $this->db->or_like('jarak_izin', $q);
    $this->db->or_like('durasi_izin', $q);
    $this->db->or_like('pelanggaran', $q);
    $this->db->or_like('prediksi', $q);
    $this->db->or_like('akurasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_data_tes', $q);
        $this->db->or_like('id_desa', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('jenis_izin', $q);
        $this->db->or_like('jarak_izin', $q);
        $this->db->or_like('durasi_izin', $q);
        $this->db->or_like('pelanggaran', $q);
        $this->db->or_like('prediksi', $q);
        $this->db->or_like('akurasi', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_tes_model.php */
/* Location: ./application/models/Data_tes_model.php */
/* Please DO NOT modify this information : */
/* This file generated by Andre Bhaskoro (+62 82 333 817 317) At : 2017-01-06 08:02:43 */
/* http://bhas.web.id */